import Head from "next/head"
import Image from "next/image"
import Header from "../components/Header"
import Banner from "../components/Banner"
import Footer from "../components/Footer"
import Smallcard from "../components/Smallcard"
import Mediumcard from "../components/Mediumcard"
import Largecard from "../components/Largecard"
import styles from "../styles/Home.module.css"

// props.exploreData becomes { exploreData } through destructuring
export default function Home({ exploreData, cardsData }) {
  return (
    <div className="">
      <Head>
        <title>Haboobs Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<Header/>
<Banner/>
    {/* banner */}
    <main className= "max-w-7xl mx-auto px-8 sm:px-16">
      <section className = "pt-6">
        <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>

          {/* Pull some data from a server - API endpoints 
           paranthesis () means it will return a jsx
          */}

          {/* 
            ES6 way:
              {exploreData?.map(({img, distance, location}) => (
            <SmallCard 
              key = {item.img}
              img = {item.img}
              distance = {item.distance}
              location = {item.location}
              />
          */}
        <div className = "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {exploreData && exploreData.map(item => (
            <Smallcard 
              key = {item.img}
              img = {item.img}
              distance = {item.distance}
              location = {item.location}
              />
          ))}
          </div>
      </section>

      <section>
      <h2 className = "text-4xl font-semibold py-8"> Inspiration for your next trip </h2>
          <div className = "flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
            {cardsData?.map(item => (
              <Mediumcard key = {item.img} img = {item.img} title = {item.title}/>
            ))}
          </div>
      </section>
      <Largecard 
      img = "https://links.papareact.com/4cj"
      title = "The Greatest Outdoor"
      description = "Things to do on your trip"
      buttonText = "get Inspired"
    />
    </main>

    <Footer />

    </div>
  )
}
// it"ll do a bunch of network work before it reaches the browser
// pre build the page on the server side, then pass it over as a  prop
// this is happening on the server only through Next js

export async function getStaticProps() {
  // call to the API, any request on the internet, we have to wait for
  const exploreData = await fetch("https://jsonkeeper.com/b/TA2T").then(
    (response) => response.json()
  );

  const cardsData = await fetch("https://jsonkeeper.com/b/GHNM").then(
    (response) => response.json()
  );
  return {
    props: {
      exploreData,cardsData
    }
  }
}
